Vagrant.configure(2) do |config|

  # config.dns.tld = "vagrant.dev"

  # Windows 2012R2
  config.vm.define "harden-windows2012" do |win2012|
    win2012.vm.box = "matt/windows2012R2"
    win2012.vm.hostname = "harden-windows2012"
    win2012.vm.network "private_network", ip: "10.77.1.44"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "harden-windows2012"
      vbox.cpus = 1
      vbox.memory = 512
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
    ansible.inventory_path = "./hosts"
  end

end
